
---
apiVersion: v1
kind: Namespace
metadata:
  name: myapp-build
  labels:
    app : myapp
    team: David Gordon
    build-namespace: myapp-build
    size: medium
    environment: build
    goldilocks.fairwinds.com/enabled: "true"
    argocd.argoproj.io/managed-by: myapp-build

---
apiVersion: v1
kind: Namespace
metadata:
  name: myapp-dev
  labels:
    app : myapp
    team: David Gordon
    build-namespace: myapp-build
    size: medium
    environment: dev
    goldilocks.fairwinds.com/enabled: "true"
    argocd.argoproj.io/managed-by: myapp-build

---
apiVersion: v1
kind: Namespace
metadata:
  name: myapp-qa
  labels:
    app : myapp
    team: David Gordon
    build-namespace: myapp-build
    size: medium
    environment: qa
    goldilocks.fairwinds.com/enabled: "true"
    argocd.argoproj.io/managed-by: myapp-build

---
apiVersion: v1
kind: Namespace
metadata:
  name: myapp-prod
  labels:
    app : myapp
    team: David Gordon
    build-namespace: myapp-build
    size: medium
    environment: prod
    goldilocks.fairwinds.com/enabled: "true"
    argocd.argoproj.io/managed-by: myapp-build
